"""empty message

Revision ID: 12a30dc974fb
Revises: 64cdf4abb556
Create Date: 2019-12-21 16:19:42.281762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12a30dc974fb'
down_revision = '64cdf4abb556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'article_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('article', 'ext_field_1',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('article', 'ext_field_2',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'ext_field_2',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('article', 'ext_field_1',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('article', 'article_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
