"""empty message

Revision ID: e8f7ab64277e
Revises: 12a30dc974fb
Create Date: 2019-12-21 16:23:23.140105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8f7ab64277e'
down_revision = '12a30dc974fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('serial', sa.Integer(), nullable=True))
    op.alter_column('article', 'article_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('article', 'ext_field_1')
    op.drop_column('article', 'ext_field_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('ext_field_2', mysql.VARCHAR(length=1024), nullable=False))
    op.add_column('article', sa.Column('ext_field_1', mysql.VARCHAR(length=1024), nullable=False))
    op.alter_column('article', 'article_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('article', 'serial')
    # ### end Alembic commands ###
